FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

#RUN apt-get update && \
#    apt-get install -y --no-install-recommends \
#        wget \
#        libdigest-sha-perl \
#        ca-certificates && \
#    mkdir  -p /opt/jdk && \
#    cd /opt/jdk/ && \
#    wget https://download.java.net/java/GA/jdk17.0.2/dfd4a8d0985749f896bed50d7138ee7f/8/GPL/openjdk-17.0.2_linux-x64_bin.tar.gz && \
#    wget https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.tar.gz.sha256 && \
#    shasum --algorithm 256 jdk-17_linux-x64_bin.tar.gz.sha256 && \
#    tar -xvzf openjdk-17.0.2_linux-x64_bin.tar.gz && \
#    update-alternatives --install /usr/bin/java java /opt/jdk/jdk-17.0.2/bin/java 100
#
#ENV JAVA_HOME="/opt/jdk/jdk-17.0.2/"

#RUN groupadd -g 1000 elasticsearch && \
#    useradd elasticsearch -u 1000 -g 1000

#RUN apt-get update &&  \
#    apt-get install -y --no-install-recommends \
#        ca-certificates \
#        wget \
#        apt-utils \
#        apt-transport-https \
#        software-properties-common \
#        gnupg && \
#    wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg && \
#    apt-key adv --keyserver pgp.mit.edu --recv-keys 46095ACC8548582C1A2699A9D27D666CD88E42B4 && \
#    echo "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main"  \
#        | tee /etc/apt/sources.list.d/elastic-8.x.list && \
#    apt-get update && \
#    apt-get install -y --no-install-recommends  \
#        elasticsearch
RUN adduser elasticsearch && \
    usermod -aG sudo elasticsearch && \
    su - elasticsearch

RUN apt-get update -y && \
    apt-get install -y \
        wget \
        ca-certificates && \
    cd /home/ &&  \
    cd elasticsearch/ && \
    wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.1.2-linux-x86_64.tar.gz && \
    tar -xvzf elasticsearch-8.1.2-linux-x86_64.tar.gz && \
    rm -rf elasticsearch-8.1.2-linux-x86_64.tar.gz


#ENV ES_JAVA_HOME="/opt/jdk/jdk-17.0.2/"

#WORKDIR /home/elasticsearch-8.1.2/bin

#RUN set -ex &&  \
#    for path in data logs config config/scripts; do \
#      mkdir -p "$path"; \
#      chown -R elasticsearch:elasticsearch "$path"; \
#    done

#COPY logging.yml /usr/share/elasticsearch/config/
#
#COPY elasticsearch.yml /usr/share/elasticsearch/config/
#
USER elasticsearch
#
ENV PATH=$PATH:/home/elasticsearch/elasticsearch-8.1.2/bin
#
##RUN systemctl daemon-reload && \
##    systemctl enable elasticsearch.service && \
##    systemctl start elasticsearch.service
#
CMD ["elasticsearch"]
#
EXPOSE 9200 9300
